# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!
target 'My First Application' do
  pod 'Alamofire', '~> 3.5.1'
  pod 'AlamofireImage', '~> 2.5.0'
  pod 'JSONModel'
  pod 'GearRefreshControl', '~> 0.1'
  pod 'AlamofireObjectMapper', '~> 2.1'


end
